### ISSUE TITLE
Where should this code reside?

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorAcsMotion#1]
Will this repo move to epics-modules, eventually?

Should it be merged with [motorAcsTech80](https://github.com/epics-motor/motorAcsTech80), which is where the legacy SPiiPlus support resides?

**Comment by keenanlang** [comment]
Eventually it should be moved to epics-motors, whether that ends up meaning it being combined with an existing module or having the entire repo move over, I'm not sure. If it gets combined with motorAcsTech80, the naming of that module should probably be changed.

**Comment by kmpeters** [comment]
> If it gets combined with motorAcsTech80, the naming of that module should probably be changed.

I agree.
