### ISSUE TITLE
Motion controller outputs engineering units instead of encoder counts

### ISSUE THREAD

**Issue by kematusik** [epics-motor/motorAcsMotion#15]
We are using a PI A-810 motion controller to move an air-bearing rotation stage. The motor controller uses ACS Motion Control and is configured to output motor position in engineering units rather than encoder counts, making it incompatible with this driver. Is there a way to make it work with this driver without making changes on the controller side? Thank you in advance.

**Comment by kmpeters** [comment]
I merged some other changes this morning that make the EPICS support work better with linear and brushless servo motors: https://github.com/epics-motor/motorAcsMotion/pull/28
