### ISSUE TITLE
Travis windows build failures

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorAcsMotion#3]
Three of the travis builds fail:

  https://travis-ci.org/github/epics-motor/motorAcsMotion/builds/715243812

All are windows builds.

**Comment by MarkRivers** [comment]
I believe the problem is the order of these 2 lines in the .cpp code:
```
#include "SPiiPlusDriver.h"

#include <epicsExport.h>
```
They need to be swapped, because SPiiPlusDriver.h defines functions that should be exported in this dll.

**Comment by kmpeters** [comment]
Thanks Mark!

Fixed by https://github.com/epics-motor/motorAcsMotion/commit/9fa7eb2b340568c2d56e7167482722d90ec91076
